// Fixed content contract. Keep these keys aligned with fields.json.
export type TextFieldKey =
  "home.hero.heading" |
  "home.hero.highlight" |
  "home.hero.intro" |
  "home.hero.primaryLabel" |
  "home.hero.primaryLink" |
  "home.hero.secondaryLabel" |
  "home.hero.secondaryLink" |
  "home.services.heading" |
  "home.services.0.title" |
  "home.services.0.description" |
  "home.services.0.link" |
  "home.services.1.title" |
  "home.services.1.description" |
  "home.services.2.title" |
  "home.services.2.description" |
  "home.about.heading" |
  "home.about.intro" |
  "home.about.bullet0" |
  "home.about.bullet1" |
  "home.about.bullet2" |
  "home.about.bullet3" |
  "home.contact.heading" |
  "home.contact.intro" |
  "home.seo.title" |
  "home.seo.description" |
  "ads.hero.badge" |
  "ads.hero.heading" |
  "ads.hero.intro" |
  "ads.hero.primaryLabel" |
  "ads.hero.primaryLink" |
  "ads.hero.secondaryLabel" |
  "ads.hero.secondaryLink" |
  "ads.services.heading" |
  "ads.services.0.title" |
  "ads.services.0.description" |
  "ads.services.1.title" |
  "ads.services.1.description" |
  "ads.services.2.title" |
  "ads.services.2.description" |
  "ads.about.heading" |
  "ads.about.intro" |
  "ads.about.bullet0" |
  "ads.about.bullet1" |
  "ads.about.bullet2" |
  "ads.about.bullet3" |
  "ads.contact.heading" |
  "ads.contact.intro" |
  "ads.seo.title" |
  "ads.seo.description" |
  "shared.profile.name" |
  "shared.profile.role" |
  "shared.profile.linkedin" |
  "shared.profile.linkLabel" |
  "shared.reviews.heading" |
  "shared.reviews.intro" |
  "shared.reviews.0.name" |
  "shared.reviews.0.business" |
  "shared.reviews.0.quote" |
  "shared.reviews.1.name" |
  "shared.reviews.1.business" |
  "shared.reviews.1.quote" |
  "shared.reviews.2.name" |
  "shared.reviews.2.business" |
  "shared.reviews.2.quote" |
  "shared.contact.email" |
  "shared.contact.phone" |
  "shared.contact.phoneLink" |
  "shared.nav.servicesLabel" |
  "shared.nav.servicesLink" |
  "shared.nav.aboutLabel" |
  "shared.nav.aboutLink" |
  "shared.nav.contactLabel" |
  "shared.nav.contactLink" |
  "shared.footer.message" |
  "shared.footer.copyright" |
  "shared.footer.topLabel" |
  "shared.footer.topLink";
export type ImageFieldKey = "home.seo.image" | "ads.seo.image" | "shared.profile.image";
export interface ImageValue { src: string; assetId: string | null; description: string; width: number; height: number; x: number; y: number; }
export interface SiteContent { schemaVersion: 1; values: Record<TextFieldKey, string> & Record<ImageFieldKey, ImageValue>; }
